### ISSUE TITLE
Support for REGEX and DIRECTION in SIP Servlets Management console

### ISSUE THREAD

**Issue by deruelle** [Mobicents/sip-servlets#6]
See https://code.google.com/p/mobicents/issues/detail?id=2577

**Comment by jaimecasero** [comment]
As discussed by email i suggest to have a free field for optionalParams/PlatformSpecific fields.

**Comment by deruelle** [comment]
That probably makes sense for now. Can you attach a snapshot pic of the new field and another one with how the DAR source looks like ?
