### ISSUE TITLE
Hosting in AWS Cloud

### ISSUE THREAD

**Issue by subu1979** [Mobicents/sip-servlets#69]
We have hosted the SIP Servlets 3.0.564 (tomcat) app in AWS . This works fine for localhost. How to give the public IP to the connector tag.

**Comment by deruelle** [comment]
Please use the forums for questions https://groups.google.com/group/mobicents-public or http://stackoverflow.com/search?tab=newest&q=mobicents not the issue tracker. Thanks in advance
