### ISSUE TITLE
Releases are not up to date ?

### ISSUE THREAD

**Issue by dgutzeit** [Mobicents/sip-servlets#71]
I see artefacts for version 4.x and tomcat8 support on Maven, but there are no such version on the "Releases" section of the GitHub project. Is there any other location for download ?

**Comment by dgutzeit** [comment]
For anyone searching, mentioned releases can be located here: https://mobicents.ci.cloudbees.com/job/MobicentsSipServlets-4.X-Release/17/artifact/

But it would be also nice to see it on GitHub as well :)

**Comment by deruelle** [comment]
That's still preview releases. 4.X is still a work in progress notably on Wildfly JBoss AS 8 support.

The 3.X stable branch is here https://mobicents.ci.cloudbees.com/job/MobicentsSipServlets-Release.  We still need to close https://github.com/Mobicents/sip-servlets/issues/60 before making an official release. Let me know if you'd be interested in contributing it.

**Comment by deruelle** [comment]
This is not available here in BETA release https://github.com/Mobicents/sip-servlets/releases
