### ISSUE TITLE
Scanning for anotations takes too long

### ISSUE THREAD

**Issue by pchlupacek** [Mobicents/sip-servlets#73]
The SipContextConfig,java contains scanning for SipApplication annotations. This traverses a whole tree of classes in jar's of war. If you use some JVM languages that do tent to generate lot of class files (i.e. scala), this traversal may take ages, effectively causing server to fail to start. 

There is no option to turn this off altogether or just limit it to concrete jar, likewise it is in catalina.properties. 

I would suggest to add that as option to some mobicents configuration file, or perhaps if feasible hook this to catalina.properties standrad balcklist functionality.

**Comment by deruelle** [comment]
Yes it is a known issue See Issue #38. Would you want to contribute to it ? Please comment on the other issue no have scattered comments on the same issue
