### ISSUE TITLE
Memory leak in StandardSipApplicationSessionTimerService and ProxyTimerService

### ISSUE THREAD

**Issue by AlerantAppNGIN** [Mobicents/sip-servlets#80]
The org.mobicents.servlet.sip.core.timers.StandardSipApplicationSessionTimerService and the org.mobicents.servlet.sip.core.timers.ProxyTimerService classes both extend java.util.Timer. There is a queue for timer tasks in this class which grows constantly if these tasks not timed out but instead cancelled using cancel() method calls. A possible solution would be to call the class’s purge() method periodically.

Already there is a property for this purpose called canceled-timer-tasks-purge-period (see http://docs.telestax.com/sip-servlets-sip-connectors/), but it has been used by only 
org.mobicents.servlet.sip.core.timers.DefaultSipApplicationSessionTimerService and 
org.mobicents.servlet.sip.core.timers.TimerServiceImpl classes.

**Comment by deruelle** [comment]
Pull request merged. Closing issue
