### ISSUE TITLE
Running Sip-Servlet JBoss AS7  on JDK1.8 blocks at startup

### ISSUE THREAD

**Issue by jaimecasero** [Mobicents/sip-servlets#82]
Seems JBoss related, as there are many people reporting the same with jboss7.1.1. It is suggested to wait when migration to Wildfly is ready. Just opening fot the record.

**Comment by deruelle** [comment]
We won't be able to fix that one as it is a limitation of JBoss 7 itself. People can use JBoss AS 8 now or EAP 6.4 to overcome that
